apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-starter
  labels:
    app: java-starter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-starter
  template:
    metadata:
      labels:
        app: java-starter
    spec:
      containers:
        - name: app
          image: ghcr.io/OWNER/REPO:latest # TODO: set your image
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "8080"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"